FROM python:3.9

RUN mkdir /app
WORKDIR /app
COPY requirements_api.txt /app/requirements_api.txt
RUN pip3 install -r /app/requirements_api.txt
COPY . /app

ENTRYPOINT ["python"]
CMD ["./src/flask_api.py"]
